* Bugs
** [#A] Mediaplaylist Encode displays winsize+1 chunks, must be winsize.
** TODO [#B] Show target duration as nearest greater integer.
* Features
** [#A] CR/LF protection: characters within a quoted-string MUST NOT include linefeed (0xA), carriage-return (0xD) or double quote (0x22). :draft12:validation:
** [#A] Support EXT-X-I-FRAMES-ONLY tag																	 :v4:
** [#A] EXT-X-BYTERANGE MUST NOT appear in a Master Playlist :draft12:validation:
** [#A] The EXT-X-TARGETDURATION tag MUST NOT appear in a Master Playlist. :draft12:validation:
** [#A] The sequence number MUST NOT decrease.	 :draft12:validation:
** [#A] The EXT-X-STREAM-INF tag MUST NOT appear in a Media Playlist. :validation:draft12:
** [#A] The EXT-X-PLAYLIST-TYPE tag MUST NOT appear in a Master Playlist. :draft12:validation:
** [#A] Add support for EXT-X-PLAYLIST-TYPE in media playlists.
** [#A] A Live Playlist MUST NOT contain the EXT-X-PLAYLIST-TYPE tag. :validation:draft12:
** [#A] If o is not present, a previous media segment MUST appear in the Playlist file and MUST be a sub-range of the same media resource. :validation:draft12:
** [#B] Write more detailed test for Widevine specific parameters.
** [#B] Test cache logic for media playlists.
** [#B] Support EXT-X-PROGRAM-DATE-TIME tag
** [#B] Count EXT-X-MEDIA-SEQUENCE precense — MUST be present only once.
** [#B] Support ASSOC-LANGUAGE parameter for EXT-X-MEDIA :rfc5646:draft12:
** [#B] Support for EXT-X-START tag											 :v4:draft12
** [#C] Keep extra data (any commenta out of HLS specs) in a special parameter and print it untouched with Encode.
** [#C] Add examples of playlists with #EXT-X-KEY
